apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-db
    port: 5432
    database: keycloak
    username: keycloak
    passwordSecret:
      name: keycloak-db-credentials
      key: password
  ingress:
    enabled: false
  http:
    httpEnabled: true
  hostname:
    strict: false
  proxy:
    headers: xforwarded