apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: keycloak
  repo: oci://registry-1.docker.io/bitnamicharts
  version: 17.3.3
  releaseName: keycloak
  namespace: keycloak
  valueFiles:
  - values.yaml