apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # CRDS
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.0/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.0/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  # Operator
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.0/kubernetes/kubernetes.yml
  # Database
  - postgres.yaml
  # Keycloak
  - keycloak.yaml