apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
spec:
  certificates:
    - pomerium/pomerium-dev
  secrets: pomerium/bootstrap
  authenticate:
    url: https://authenticate.pomerium.dev 
  identityProvider:
    provider: keycloak
    url: https://keycloak.pomerium.dev
    clientId: pomerium
    clientSecret:
      secretName: pomerium/keycloak-client-secret
      secretKey: client-secret