apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/pomerium/ingress-controller/config/default?ref=v0.28.0
  - github.com/pomerium/documentation/k8s/core?ref=0-28-0
