apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: v0.79.2
  releaseName: kube-prometheus-stack
  namespace: monitoring
