apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.79.2/bundle.yaml

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 67.10.0
  releaseName: prometheus-stack
  namespace: monitoring
