apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ceph-monitors.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 67.10.0
  releaseName: prometheus

patches: 
- path: grafana-auth.yaml