apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-drive-pvc
  namespace: guacamole
spec:
  storageClassName: ceph-block
  volumeMode: Block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-record-pvc
  namespace: guacamole
spec:
  storageClassName: ceph-block
  volumeMode: Block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
