apiVersion: v1
kind: Pod
metadata:
  name: ssh-pod
  labels:
    app: ssh-pod
spec:
  containers:
    - name: ssh-container
      image: ubuntu:22.04
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -ex
          
          # Install OpenSSH server
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server
          
          # Create a non-root user named 'sshuser' with an empty password (but no interactive password login)
          useradd -m -d /home/sshuser -s /bin/bash sshuser
          
          # Prepare the SSH directory
          mkdir -p /home/sshuser/.ssh
          cp /authorized_keys /home/sshuser/.ssh/authorized_keys
          chown -R sshuser:sshuser /home/sshuser/.ssh
          chmod 700 /home/sshuser/.ssh
          chmod 600 /home/sshuser/.ssh/authorized_keys
          
          # Update sshd_config to disable password authentication and root login
          sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
          sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
          echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
          
          # Make sure runtime directory exists for sshd
          mkdir -p /run/sshd
          
          # Generate host keys (needed if none exist yet)
          ssh-keygen -A
          
          # Run sshd in the foreground, logging to stderr
          exec /usr/sbin/sshd -D -e
      ports:
        - containerPort: 22
          name: ssh
      volumeMounts:
        - name: ssh-keys
          mountPath: /authorized_keys
          subPath: authorized_keys

  volumes:
    - name: ssh-keys
      configMap:
        name: ssh-config
        items:
          - key: authorized_keys
            path: authorized_keys
