apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
data:
  # Wes's key
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUOyPVCvwCIIQYq6C5pD8N8YRB8+pEykrg50ukopzp3+1hD2+dy3/S/grzxXsZZ7c+DXT5nSGqwbQGA0hkLEV0IvdcOlDpkPYbWq+gx5Xl3L4/E50LgfCQPQaQh+USgCxm6UAnpn0hz/XIcK0788xo4UdbAXoo5O6uZ4X2Brb27yER3m5cDUaYyaEaNDOHCl5ffMa1dc0QMbCs42urIiHYMXUgvFiK/tZ8amGOAwELoqnFCGLP7xqu+nyD2vFgxxqjkhy2CzzQzdMwPpHu91xalyIuZ+b5VQyzCayE0gzCYHvNGOyR9/mX9dsN+/JB3SAaRVhNM2FnQ/9KJ0g8d5HX4wbSXjNTHrk0QOUE8Z3jxK5D4YO9dQdTjCCoxD/Tm0HhqiWYAGkWL9yCjBslgd3xK2eVCyJyEV9PW8d9XZkuaL7H+fPuHWTpWGjexlKrQtFjZY19k51OVP0iS36907CDFLaomUadsfy32p4rC9vxOpwRUk7aOKExuvxZ+CiGSZ0=
