apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
          - server
          - http://pomerium-1/data
          - http://pomerium-2-c7d580ec/data
          - http://pomerium-3-5300c67e/data
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data1
          mountPath: /data/pomerium-1
        - name: data2
          mountPath: /data/pomerium-2
        - name: data3
          mountPath: /data/pomerium-3
      volumes:
      - name: data1
        persistentVolumeClaim:
          claimName: minio-pvc-1
      - name: data2
        persistentVolumeClaim:
          claimName: minio-pvc-2
      - name: data3
        persistentVolumeClaim:
          claimName: minio-pvc-3
