---
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio-tenant
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
    export MINIO_STORAGE_CLASS_STANDARD="XL:3"
    export MINIO_BROWSER="on"
type: Opaque
---
# Console login credentials (optional) - base64-decoded = "console" / "console12"
apiVersion: v1
kind: Secret
metadata:
  name: storage-user
  namespace: minio-tenant
data:
  CONSOLE_ACCESS_KEY: Y29uc29sZQ==
  CONSOLE_SECRET_KEY: Y29uc29sZTEyMw==
type: Opaque
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: myminio
  namespace: minio-tenant
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
  labels:
    app: minio
spec:
  # Points to the config.env in the 'storage-configuration' Secret
  configuration:
    name: storage-configuration

  # MinIO image for the server pods
  image: quay.io/minio/minio:RELEASE.2024-10-02T17-50-41Z

  # Where the volumes are mounted inside each container
  mountPath: /export

  # For starting up all pods in parallel
  podManagementPolicy: Parallel

  # Number of pods, volumes, and scheduling constraints are defined per "pool"
  pools:
    - name: pool-0
      servers: 4               # We want exactly 3 MinIO pods
      volumesPerServer: 2      # 2 PVC per node
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1.8Ti

        # Enforce that no two pods land on the same node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                # By default, the operator labels MinIO pods with "v2.min.io/tenant=<tenantName>"
                matchLabels:
                  v2.min.io/tenant: myminio
              topologyKey: kubernetes.io/hostname

  # Automatically request TLS certificates (optional)
  requestAutoCert: true

  # Example user for your MinIO instance
  users:
    - name: storage-user
