apiVersion: kustomize.config.k8s.io/v1beta1
type: kustomization

resources:
  helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
    version: v1.16.3
    valuesInline:
      crds:
        enabled: true