apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
  - namespace.yaml

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: 0.29.1
    releaseName: rook-ceph
    namespace: rook-ceph
