---
clusterName: pomerium-demo
talosVersion: v1.9.0
kubernetesVersion: v1.32.0

# NOTE: We do NOT use the VIP as the Talos endpoint.
# This is intentional to avoid issues if etcd is down.
endpoint: https://192.168.68.101:6443
domain: ${myDomainName}
allowSchedulingOnMasters: false

additionalMachineCertSans:
  - 192.168.68.150
additionalApiServerCertSans:
  - pomerium-demo.local
  - 127.0.0.1

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12

cniConfig:
  name: none  # We'll install cilium after Talos is up

################################################################################
# CONTROL PLANE (global defaults for master nodes)
################################################################################
controlPlane:
  machineSpec:
    mode: metal
    arch: amd64

  # Each UM773 has a 1TB NVMe for Talos installation
  installDiskSelector:
    size: 1TB
    type: nvme

  ingressFirewall:
    defaultAction: block
    rules:
      - name: kubelet-ingress
        portSelector:
          ports:
            - 10250
          protocol: tcp
        ingress:
          # All control-plane nodes are on 192.168.68.x
          - subnet: 192.168.68.0/24

  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
          rotate-server-certificates: "true"
    - "@./extraKernelArgs-patch.yaml"

  # Common node labels, taints, annotations
  nodeLabels:
    rack: demo-rack
    use: control-plane
    manufacturer: Minisforum
    model: UM773-Lite

  nodeAnnotations:
    rack: demo-rack

  # Common kernel module config
  kernelModules:
    - name: br_netfilter
      parameters:
        - nf_conntrack_max=131072
    - name: k10temp

  nameservers:
    - 1.1.1.1
    - 8.8.8.8

  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/amd-ucode

################################################################################
# WORKER (global defaults for worker nodes)
################################################################################
worker:
  machineSpec:
    mode: metal
    arch: amd64

  # Most worker nodes have a 500GB OS disk; you can adjust as suits your hardware.
  installDiskSelector:
    size: '<=1TB'
    type: nvme

  # Example: data disks for worker nodes (for Ceph or other usage).
  machineDisks:
    - size: '>1.2TB'
      type: nvme

  ingressFirewall:
    defaultAction: block
    rules:
      - name: apid-ingress
        portSelector:
          ports:
            - 50000
          protocol: tcp
        ingress:
          - subnet: 10.96.0.0/12

  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=false,MixedProtocolLBService=false
          rotate-server-certificates: "true"
      - op: add
        path: /machine/networkInterfaces/0/routes
        value:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1

  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/thunderbolt
          - siderolabs/intel-ucode

  nodeLabels:
    rack: demo-rack
    use: worker
  nodeAnnotations:
    rack: demo-rack

  disableSearchDomain: true

  kernelModules:
    - name: br_netfilter
      parameters:
        - nf_conntrack_max=131072

  nameservers:
    - 1.1.1.1
    - 8.8.8.8

################################################################################
# NODES (specific configs, overriding global where needed)
################################################################################
nodes:
  #--------------------------------------------------------------------------
  # CONTROL PLANE
  #--------------------------------------------------------------------------
  - hostname: main1
    controlPlane: true
    ipAddress: 192.168.68.101
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.68.101/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        mtu: 1500
        # Add VIP config so all masters share the same floating IP
        vip:
          ip: 192.168.68.150

  - hostname: main2
    controlPlane: true
    ipAddress: 192.168.68.102
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.68.102/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        mtu: 1500
        vip:
          ip: 192.168.68.150

  - hostname: main3
    controlPlane: true
    ipAddress: 192.168.68.103
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.68.103/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        mtu: 1500
        vip:
          ip: 192.168.68.150

  #--------------------------------------------------------------------------
  # WORKERS
  #--------------------------------------------------------------------------
  - hostname: kworker1
    controlPlane: false
    ipAddress: 192.168.68.111

  - hostname: kworker2
    controlPlane: false
    ipAddress: 192.168.68.112

  - hostname: kworker3
    controlPlane: false
    ipAddress: 192.168.68.113

  - hostname: kworker4
    controlPlane: false
    ipAddress: 192.168.68.114
    installDiskSelector:
      size: '<=2TB'
      type: ssd
    machineDisks:
      - size: '<=2TB'
        type: ssd
      - size: '<=2TB'
        type: ssd
    nodeLabels:
      manufacturer: Custom
      gpu: true
      gpu.model: NVIDIA RTX 3090
      gpu.count: 2
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/thunderbolt
            - siderolabs/nvidia-driver
            - siderolabs/nvidia-container-runtime
            - siderolabs/nvidia-gpu-device-plugin
            - siderolabs/amd-ucode
    kernelModules:
      - name: k10temp
