---
clusterName: pomerium-demo
talosVersion: v1.9.0
kubernetesVersion: v1.32.0

# NOTE: We do NOT use the VIP as the Talos endpoint.
# This is intentional to avoid issues if etcd is down.
endpoint: https://192.168.68.100:6443
domain: pomerium-demo.com
allowSchedulingOnMasters: false

additionalMachineCertSans:
  - 192.168.68.150
additionalApiServerCertSans:
  - pomerium-demo.local
  - 127.0.0.1

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12

cniConfig:
  name: none  # We'll install cilium after Talos is up

################################################################################
# CONTROL PLANE (global defaults for master nodes)
################################################################################
controlPlane:
  machineSpec:
    mode: metal
    arch: amd64

  ingressFirewall:
    defaultAction: block
    rules:
      - name: kubelet-ingress
        portSelector:
          ports:
            - 10250
          protocol: tcp
        ingress:
          # All control-plane nodes are on 192.168.68.x
          - subnet: 192.168.68.0/24

  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
          rotate-server-certificates: "true"

  # Common node labels, taints, annotations
  nodeLabels:
    rack: demo-rack
    use: control-plane
    manufacturer: Minisforum
    model: UM773-Lite

  nodeAnnotations:
    rack: demo-rack

  # Common kernel module config
  kernelModules:
    - name: br_netfilter
      parameters:
        - nf_conntrack_max=131072
    - name: k10temp

  nameservers:
    - 1.1.1.1
    - 8.8.8.8

  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/amd-ucode

################################################################################
# WORKER (global defaults for worker nodes)
################################################################################
worker:
  machineSpec:
    mode: metal
    arch: amd64

  ingressFirewall:
    defaultAction: block
    rules:
      - name: apid-ingress
        portSelector:
          ports:
            - 50000
          protocol: tcp
        ingress:
          - subnet: 10.96.0.0/12

  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=false,MixedProtocolLBService=false
          rotate-server-certificates: "true"

  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/thunderbolt
          - siderolabs/intel-ucode
          - siderolabs/mei

  nodeLabels:
    rack: demo-rack
    use: worker
  nodeAnnotations:
    rack: demo-rack

  disableSearchDomain: true

  kernelModules:
    - name: br_netfilter
      parameters:
        - nf_conntrack_max=131072

  nameservers:
    - 1.1.1.1
    - 8.8.8.8

################################################################################
# NODES (specific configs, overriding global where needed)
################################################################################
nodes:
  #--------------------------------------------------------------------------
  # CONTROL PLANE
  #--------------------------------------------------------------------------
  - hostname: main1
    controlPlane: true
    ipAddress: 192.168.68.100
    installDiskSelector:
      type: nvme
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.68.100/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        mtu: 1500
        # Add VIP config so all masters share the same floating IP
        vip:
          ip: 192.168.68.150

  - hostname: main2
    controlPlane: true
    ipAddress: 192.168.68.101
    installDiskSelector:
      type: nvme
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.68.101/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        mtu: 1500
        vip:
          ip: 192.168.68.150

  - hostname: main3
    controlPlane: true
    ipAddress: 192.168.68.102
    installDiskSelector:
      type: nvme
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.68.102/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        mtu: 1500
        vip:
          ip: 192.168.68.150

  #--------------------------------------------------------------------------
  # WORKERS
  #--------------------------------------------------------------------------
  - hostname: kworker1
    controlPlane: false
    ipAddress: 192.168.68.110
    installDiskSelector:
      size: "<1TB"
      type: nvme
    machineDisks:
      - size: 2TB
        type: nvme
      - size: 2TB
        type: nvme

  - hostname: kworker2
    controlPlane: false
    ipAddress: 192.168.68.111
    installDiskSelector:
      size: "<1TB"
      type: nvme
    machineDisks:
      - size: 2TB
        type: nvme
      - size: 2TB
        type: nvme   

  - hostname: kworker3
    controlPlane: false
    ipAddress: 192.168.68.112
    installDiskSelector:
      size: "<1TB"
      type: nvme
    machineDisks:
      - size: 2TB
        type: nvme
      - size: 2TB
        type: nvme  

  - hostname: kworker4
    controlPlane: false
    ipAddress: 192.168.68.113
    installDiskSelector:
      size: '<=2TB'
      type: ssd
    machineDisks:
      - size: '<=2TB'
        type: ssd
      - size: '<=2TB'
        type: ssd
      - size: '>2TB'
        type: nvme
    nodeLabels:
      manufacturer: Custom
      gpu: true
      gpu.model: "3090"
      gpu.count: 2
    kernel:
    modules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
    sysctls:
      net.core.bpf_jit_harden: 1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/thunderbolt
            - siderolabs/amd-ucode
    kernelModules:
      - name: k10temp
