---
clusterName: pomerium-demo
talosVersion: v1.9.1
kubernetesVersion: v1.32.0

# NOTE: We do NOT use the VIP as the Talos endpoint.
# This is intentional to avoid issues if etcd is down.
endpoint: https://192.168.68.150:6443
allowSchedulingOnMasters: false

additionalMachineCertSans:
  - 192.168.68.150
  - 127.0.0.1
additionalApiServerCertSans:
  - pomerium-demo.local
  - 127.0.0.1

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12

cniConfig:
  name: none # Will use cilium as an inline manifest

################################################################################
# CONTROL PLANE (global defaults for master nodes)
################################################################################
controlPlane:
  machineSpec:
    mode: metal
    arch: amd64

  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          rotate-server-certificates: "true"
          feature-gates: GracefulNodeShutdown=true
      - op: add
        path: /cluster/controllerManager/extraArgs
        value:
          bind-address: 0.0.0.0
      - op: add
        path: /cluster/scheduler/extraArgs
        value:
          bind-address: 0.0.0.0
      - op: add
        path: /cluster/proxy/extraArgs
        value:
          bind-address: 0.0.0.0

  # Common node labels, taints, annotations
  nodeLabels:
    rack: demo-rack
    use: control-plane
    manufacturer: Minisforum
    model: UM773-Lite

  nodeAnnotations:
    rack: demo-rack

  # Common kernel module config
  kernelModules:
    - name: br_netfilter
      parameters:
        - nf_conntrack_max=131072
    - name: k10temp

  nameservers:
    - 1.1.1.1
    - 8.8.8.8

  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/amd-ucode
          - siderolabs/amdgpu
          - siderolabs/util-linux-tools
          - siderolabs/thunderbolt

################################################################################
# WORKER (global defaults for worker nodes)
################################################################################
worker:
  machineSpec:
    mode: metal
    arch: amd64

  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          rotate-server-certificates: "true"
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/openebs/local
              type: bind
              source: /var/openebs/local
              options:
                - rbind
                - rshared
                - rw

  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
        - iommu=pt
        - intel_iommu=on
        - mitigations=off
      systemExtensions:
        officialExtensions:
          - siderolabs/thunderbolt
          - siderolabs/intel-ucode
          - siderolabs/mei
          - siderolabs/util-linux-tools
          - siderolabs/intel-ice-firmware 
          - siderolabs/i915

  nodeLabels:
    rack: demo-rack
    use: worker
  nodeAnnotations:
    rack: demo-rack

  disableSearchDomain: true

  kernelModules:
    - name: br_netfilter
      parameters:
        - nf_conntrack_max=131072

  nameservers:
    - 1.1.1.1
    - 8.8.8.8

################################################################################
# NODES (specific configs, overriding global where needed)
################################################################################
nodes:
  #--------------------------------------------------------------------------
  # CONTROL PLANE
  #--------------------------------------------------------------------------
  - hostname: main1
    controlPlane: true
    ipAddress: 192.168.68.100
    installDiskSelector:
      type: nvme
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.68.100/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        mtu: 1500
        # Add VIP config so all masters share the same floating IP
        vip:
          ip: 192.168.68.150

  - hostname: main2
    controlPlane: true
    ipAddress: 192.168.68.101
    installDiskSelector:
      type: nvme
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.68.101/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        mtu: 1500
        vip:
          ip: 192.168.68.150

  - hostname: main3
    controlPlane: true
    ipAddress: 192.168.68.102
    installDiskSelector:
      type: nvme
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.68.102/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        mtu: 1500
        vip:
          ip: 192.168.68.150

  #--------------------------------------------------------------------------
  # WORKERS
  #--------------------------------------------------------------------------
  - hostname: kworker1
    controlPlane: false
    ipAddress: 192.168.68.110
    installDiskSelector:
      size: "<1TB"
      type: nvme
    machineDisks:
      - size: 2TB
        type: nvme
      - size: 2TB
        type: nvme

  - hostname: kworker2
    controlPlane: false
    ipAddress: 192.168.68.111
    installDiskSelector:
      size: "<1TB"
      type: nvme
    machineDisks:
      - size: 2TB
        type: nvme
      - size: 2TB
        type: nvme   

  - hostname: kworker3
    controlPlane: false
    ipAddress: 192.168.68.112
    installDiskSelector:
      size: "<1TB"
      type: nvme
    machineDisks:
      - size: 2TB
        type: nvme
      - size: 2TB
        type: nvme  

  - hostname: kworker4
    controlPlane: false
    ipAddress: 192.168.68.113
    installDiskSelector:
      type: ssd
      size: "<3TB"
    machineDisks:
      - type: ssd
      - type: ssd
      - type: nvme
    nodeLabels:
      manufacturer: Custom
      gpu: true
      gpu.model: "3090"
      gpu.count: 2
    sysctls:
      net.core.bpf_jit_harden: 1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/thunderbolt
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/util-linux-tools
            # - siderolabs/nvidia-container-toolkit-production
            # - siderolabs/nvidia-fabricmanager-production
            # - siderolabs/nonfree-kmod-nvidia-production
    kernelModules:
      - name: k10temp
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
