apiVersion: v1
kind: ConfigMap
metadata:
  name: enterprise
data:
  # should match authenticate service URL from Pomerium Settings CRD
  authenticate_service_url: https://authenticate.pomerium.app # use hosted authenticate
  # audience should correspond to the name in the ingress you created for the console
  # without the protocol part
  audience: console.pomerium.dev
  # administrators is a comma separated list of emails that would be granted admin privileges
  # only use it for bootstrapping, and grant explicit permissions via the UI to the Global namespace
  administrators: wmedford@pomerium.com
  # databroker service URL allows Console to communicate to Pomerium Core
  databroker_service_url: https://pomerium-databroker.pomerium.svc.cluster.local
  # external Prometheus service URL, to enable metrics.
  # see https://www.pomerium.com#metrics
  prometheus_url: https://prometheus-kube-prometheus-prometheus.default.svc.cluster.local