apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium-console
spec:
  template:
    spec:
      containers:
        - name: pomerium-console
          env:
            - name: OVERRIDE_CERTIFICATE_NAME
              valueFrom:
                configMapKeyRef:
                  key: override_certificate_name
                  name: enterprise
                  optional: true
