apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pomerium-enterprise

resources:
  - github.com/pomerium/documentation/k8s/console?ref=0-28-0
  - config.yaml
  - postgres.yaml
  - ingress.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
