apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pomerium-enterprise-db

spec:
  instances: 2

  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: pomerium
      owner: pomerium
      secret:
        name: enterprise

  resources:
    requests:
      cpu: '2'
      memory: 4Gi
