apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pomerium-enterprise-db

spec:
  instances: 2

  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
    - name: pomerium
      ensure: present
      # Do not use this configuration in a production setup
      comment: "Pomerium Enterprise Database"
      login: true
      superuser: true
      disablePassword: true
  bootstrap:
    initdb:
      database: pomerium
      owner: pomerium

  enableSuperUserAccess: true

  resources:
    requests:
      cpu: 2
      memory: 4Gi
