apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: pomerium-enterprise-db
spec:
  teamId: "pomerium"
  volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    pomerium-enterprise.pomerium:
      - superuser
      - createdb
  databases:
    pomerium: pomerium  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "17"