apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: pomerium-enterprise
spec:
  teamId: "pomerium"
  volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    wmedford:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    pomerium: wmedford  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "17"