apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block     # Adjust if your Ceph StorageClass has a different name
  resources:
    requests:
      storage: 10Gi
