apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guacamole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pomerium/demo-cluster
    targetRevision: HEAD
    path: k8s/guacamole
  destination:
    server: https://kubernetes.default.svc
    namespace: guacamole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
