apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pomerium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pomerium/demo-cluster
    targetRevision: HEAD
    path: k8s/pomerium-core
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "batch"
    kind: Job
    name: pomerium-gen-secrets
    
